# Generated by Django 2.1.7 on 2019-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_autoidtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoAutoIDTable',
            fields=[
                ('my_field', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
