# Generated by Django 2.1.7 on 2019-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0006_nulltables'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankOptionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoBlankOptionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(max_length=200)),
            ],
        ),
    ]
