# Generated by Django 2.1.7 on 2019-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0007_blackoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesOptionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(choices=[('1', 'Apple'), ('2', 'Banana'), ('3', 'Pear')], max_length=200)),
            ],
        ),
    ]
