# Generated by Django 2.1.7 on 2019-04-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0008_choiceoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultStringTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(default='HelloWorld', max_length=200)),
            ],
        ),
    ]
