# Generated by Django 2.1.7 on 2019-04-20 02:32

from django.db import migrations, models
import myfirstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0009_defaultstringoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCallableOptionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(default=myfirstapp.models.my_callable_object, max_length=200)),
            ],
        ),
    ]
