# Generated by Django 2.1.7 on 2019-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0011_help_text_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryKeyOptionTable',
            fields=[
                ('my_field', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
