# Generated by Django 2.1.7 on 2019-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0012_primarykeyoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueOptionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
